{"name": "testxfail", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert False", "trace": "@pytest.mark.xfail\n    def testxfail():\n        print(\"failed\")\n>       assert False\nE       assert False\n\npython\\selenium\\dr\\pytest_test_programming\\test_pytestexampleAssertion.py:31: AssertionError"}, "attachments": [{"name": "stdout", "source": "316b4cf1-373b-4f99-b631-301bbd32ed9c-attachment.txt", "type": "text/plain"}], "start": 1720110563077, "stop": 1720110563078, "uuid": "b293d5d6-459c-4735-988a-37f72c0fde18", "historyId": "17185a4a423497f0ad2791ab0318bf82", "testCaseId": "17185a4a423497f0ad2791ab0318bf82", "fullName": "python.selenium.dr.pytest_test_programming.test_pytestexampleAssertion#testxfail", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "python.selenium.dr.pytest_test_programming"}, {"name": "suite", "value": "test_pytestexampleAssertion"}, {"name": "host", "value": "DESKTOP-UI2KGFP"}, {"name": "thread", "value": "13356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "python.selenium.dr.pytest_test_programming.test_pytestexampleAssertion"}]}